### ISSUE TITLE
Full sample for injecting hrRoot with $routeProvider

### ISSUE THREAD

**Issue by githubUser919** [petejohanson/angular-hy-res#1]
Hi, in the docs you say that the easiest way to inject the hrRoot service is to use a resolve in the route config. I'm struggling with this and hoping you can help or supply a working example that uses this technique (angular-hy-res-example doesn't use this technique).

Here's what I'm trying (assume that ``http://my-server/api`` is a my HAL API's root URI):

```
// index.html (just before closing body tag)

<script src="app/bower_components/angular/angular.min.js"></script>
<script src="app/bower_components/angular-route/angular-route.js"></script>
<script src="app/bower_components/angular-hy-res/dist/angular-hy-res-full.js"></script>
<script src="app/bower_components/angular-hy-res/dist/angular-hy-res-hal.min.js"></script>
<script src="app/app.js"></script>


// app.js
angular.module("app", [
        'ngRoute'
        , 'angular-hy-res'
        , 'angular-hy-res-hal'])

        .config(["$routeProvider", "hrRoot", function($routeProvider, hrRoot) {
            $routeProvider
                .when("/refdata", {
                resolve: {
                    root: function(hrRoot) {
                        return hrRoot('http://my-server/api').follow().$promise;
                    }
                },
                controller: "MainCtrl",
                controllerAs: "vm",
                template: "<div>{{vm.thing}}</div>"
            })
        }]);
```

Versions:
* Angular 1.3.14
* Angular Route 1.3.14
* Latest versions of angular-hy-res

The error I'm getting is:
```
Failed to instantiate module app due to:
Error: [$injector:unpr] http://errors.angularjs.org/1.3.14/$injector/unpr?p0=hrRoot
    at Error (native)
    at http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:6:417
    at http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:38:7
    at d (http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:36:13)
    at Object.e [as invoke] (http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:36:283)
    at d (http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:34:498)
    at http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:35:117
    at s (http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:7:302)
    at g (http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:34:399)
    at ab (http://localhost:63342/angular-hy-res/app/bower_components/angular/angular.min.js:38:135
```

As far as I can tell, it's my attempt to inject the hrRoot service in the value for "resolve" when defining the route config. I believe this is the case because the following makes the injector error go away (but of course this doesn't inject the required service at all) - note that all I've done below is remove any mention of hrRoot.

```
angular.module("app", [
        'ngRoute'
        , 'angular-hy-res'
        , 'angular-hy-res-hal'])

        .config(["$routeProvider", function($routeProvider) {
            $routeProvider
                .when("/refdata", {
                resolve: {
                    root: function() {
                        return "some arbitrary value"; // hrRoot('http://localhost:62481/api/version').follow().$promise;
                    }
                },
                controller: "MainCtrl",
                controllerAs: "vm",
                template: "<div>{{vm.thing}}</div>"
            })
        }])
```

Any insight would be very much appreciated!

Thanks

**Comment by petejohanson** [comment]
.config(["$routeProvider", "hrRoot", function($routeProvider, hrRoot) {

`hrRoot` is a service that isn't available for injection during the config phase of AngularJS. Remove the reference there and leave it in your `root` resolve function, and it should work as expected.

Leaving this open until I have a chance to include an example in the sample app.

**Comment by petejohanson** [comment]
Check out my changes in https://github.com/petejohanson/angular-hy-res-example/commit/f84042e661d8862ac9db80dc538df54b3362ba4e

For how I modified the sample to demonstrate that approach.

Let me know if you have any further questions.

Thanks!

**Comment by githubUser919** [comment]
Great, I'll have a look at that changeset.

Thanks!

**Comment by petejohanson** [comment]
I'm going to mark this as closed. If you still have any questions/issues, please feel free to reopen.

Thanks.
