### ISSUE TITLE
Get all avaiable forms

### ISSUE THREAD

**Issue by XVincentX** [petejohanson/angular-hy-res#11]
Hello!
Given that I should not access private variables such as `$$forms`, how can I retrieve all available forms for a Siren resource?

Would be possible to have this behavior when passing no arguments  the `$form` method? Something like `$form()`

**Comment by petejohanson** [comment]
What is the use case for accessing all the forms? I think I would rather `Resource#$forms()` as that is more in line with the similar `Resource#$links(rel)` to get all links with a given link relation.

Would that work?

**Comment by XVincentX** [comment]
The thing is that I have got a siren resource with several actions (confirm/delete/notify).
I would like to build a complete dynamic button bar, created cycling all available actions on the given resource, and not hardcode them in advance.

Does this clarify my use case?

**Comment by petejohanson** [comment]
Makes perfect sense. I think returning an array makes sense for this, not an object keyed off the name, since the most common use case would be iterating for a dynamic UI.

I will add this to core `hy-res`.

**Comment by XVincentX** [comment]
I agree for an array.

Btw, you can iterate on a Json object keys as well in [different](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) [ways](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

**Comment by petejohanson** [comment]
Agreed that it isn't hard to iterate the keys/values, but I think it's just the slightest bit more intuitive that `$forms()` return an array.

**Comment by XVincentX** [comment]
Sure sure, just pointing out. I'll wait for next release.

**Comment by petejohanson** [comment]
Released in angular-hy-res@0.0.17/hy-res@0.0.11.

**Comment by XVincentX** [comment]
Working as expected. Great.

**Comment by XVincentX** [comment]
@petejohanson I think the same thing should be done with `$links()` function.

**Comment by petejohanson** [comment]
Indeed. Created petejohanson/hy-res#1 issue for this.

**Comment by XVincentX** [comment]
Great. Looking forward to see it!

**Comment by XVincentX** [comment]
@petejohanson Any updates?

**Comment by petejohanson** [comment]
The issue is closed, but I haven't pushed a new release yet. I was hoping to wrap up the Collection+JSON work I've been doing, but so far that's only internal changes with no external API impact, if you need the `$links()` support sooner, let me know and I can publish a release tonight.

**Comment by XVincentX** [comment]
I definitely do!

**Comment by petejohanson** [comment]
Published angular-hy-res@0.0.19 (and hy-res@0.0.12) with the change.
