### ISSUE TITLE
Do not package coredumps.

### ISSUE THREAD

**Issue by ChALkeR** [petejohanson/angular-hy-res#12]
*Disclaimer: I do not use the package, this was found during automated npm packages downloading.*

Your current package size is 4.1 MiB packed, **1.1 GiB** unpacked. 1.1 GiB of that is the `phantomjs.core` file. I think that this probably got packed to the release by mistake.

Filetype: ``ELF 64-bit LSB core file x86-64, version 1 (FreeBSD), FreeBSD-style, from 'js'``.

You should probably remove that from the release and add coredumps to the `.npmignore`.

**Comment by petejohanson** [comment]
Indeed, good catch. FIxed in v0.0.18 I just published.
