### ISSUE TITLE
HyRes does not work with StrictDI

### ISSUE THREAD

**Issue by XVincentX** [petejohanson/angular-hy-res#14]
When I enable **strictDI** option for my application, I am getting an error about your module.

![screen shot 2015-06-28 at 12 26 43](https://cloud.githubusercontent.com/assets/1416224/8395974/fcc6ac82-1d90-11e5-8024-06712849f669.png)

Could you verify if everything is annotated properly?

**Comment by petejohanson** [comment]
Fixed in master. Will be included in the next release.

Thanks!

**Comment by XVincentX** [comment]
Thanks! Looking forward for a new release then!

**Comment by petejohanson** [comment]
Give v0.0.25 a try.

**Comment by XVincentX** [comment]
@petejohanson 

After updating to 0.0.25 as well 0.0.26, I am getting this error when trying to execute an action specified in the resource

![image](https://cloud.githubusercontent.com/assets/1416224/8638711/3669389a-28c4-11e5-98ae-54306e4d8671.png)

**Comment by petejohanson** [comment]
Very odd... I am gone for a week for a trip to someone's wedding, I will look at this as soon as I am back.

In the meantime, can you capture the properties of the `Form` instance that raises the error? In particular, it looks like this would only occur if the `href` propert of the `Form instance isn't set. Looking at the response body of your client, it seems like the actions all have `href` set properly, so I'm curious what is going on here.

**Comment by XVincentX** [comment]
@petejohanson I am afraid will be out for some days as well.
By the way, the bug is fully reproducible cloning [this branch](https://github.com/XVincentX/pollsApiClient/tree/XVincentX/district)

Thanks, in meantime!

**Comment by petejohanson** [comment]
Please give new angular-hy-res@0.0.27 and hy-res@0.0.19 a try. We were not handling `201 Created` responses from form submissions if they didn't include a `Location` header. We now gracefully fall back to previous behaviour in that case.

**Comment by XVincentX** [comment]
Solved. Thank you.
