### ISSUE TITLE
hrRoot factory returns undefined

### ISSUE THREAD

**Issue by julienlafont** [petejohanson/angular-hy-res#2]
Hello!

I'm trying to integrate your lib which seem very useful.
My first tries have failed due to an error when I call `hrRoot("/users").follow()" with the error `Cannot read property 'follow' of undefined`.

By checking the code, I don't understand how it should work because the hrRoot factory doesn't return anything.

```javascript
module.factory('hrRoot', ['hrWebLink', 'hrResource', '$http', function(hrWebLink, hrResource, $http) {
    return function(url, options) {
      this.follow = function() {
        return new hrWebLink({ href: url }, $http, hrResource).follow(options);
      };
      // No return here?
    };
  }]);
```

See this fiddle for more details http://jsfiddle.net/4t7drch8/.
Is it me who doesn't see something or it can't work?

**Comment by petejohanson** [comment]
`hrRoot` is not really a traditional 'service', in the AngularJS sense, it is really a constructor function that you need to invoke using the JS `new` operator, e.g.:

    new hrRoot("/users").follow()

Take a look at this fork of your Fiddle: http://jsfiddle.net/ru775h3r/

**Comment by petejohanson** [comment]
You can see a live example in the sample app: https://github.com/petejohanson/angular-hy-res-example/blob/master/client/app/main/main.js#L12

**Comment by julienlafont** [comment]
OK you're right, it works fine like this. I havn't had the idea to test like that.
Maybe you should add a few word about that in the document, it's relatively uncommon.

Thanks for you help.

**Comment by petejohanson** [comment]
In this case, the code didn't match the docs, nor was it particularly intuitive. In addition, it did not match the similar API from `$resource`, so I've just pushed v0.0.10 that changes this to allow regular function call without the `new`.


Thanks for the report.
