### ISSUE TITLE
The module does not honor the given api endpoint

### ISSUE THREAD

**Issue by XVincentX** [petejohanson/angular-hy-res#5]
Hey,
I am using this simple code to try an hypermedia API

```javascript
export default class pollsService {
  constructor(hrRoot) {
    this.mainLink = hrRoot('http://suerapi.org').follow({ headers: { Accept: 'application/hal+json' } })

    this.mainLink.$promise.then((hrRootLink)=> {
        console.info("Fetched")
        this.hrRootLink = hrRootLink
        hrRootLink.$$links.questions[0].follow().$promise.then((q) =>{console.info(q)})
    }, (error) => {console.log(`Error during hypermedia fetching: ${error}`)})

  }
}
```

Even if the first request is correctly issued to **http://suerapi.org**, the following one are not appending the host given in the first call.

![image](https://cloud.githubusercontent.com/assets/1416224/7221646/c4b28d2c-e6f2-11e4-9a55-87d45c5f5d3b.png)

I was expecting to see **http://suerapi.org/questions**

Am I missing something here?

**Comment by petejohanson** [comment]
@XVincentX Can you add the HAL response for the root here? My hunch is the responses is a relative one, instead of an absolute URL.

I have a long standing TODO item about handling relative URL resolution prope rly, I have a feeling that is the issue you are encountering.

**Comment by XVincentX** [comment]
Yes, I confim that the returned urls are relative!

**Comment by petejohanson** [comment]
@XVincentX Please give angular-hy-res v0.0.14 a try, and let me know if things are improved. I've added relative URL handling to hy-res, and bumped both core hy-res and angular-hy-res accordingly.

Thanks.

**Comment by XVincentX** [comment]
Hey,
it works, it is correctly constructing relative url, but the **Accept** header, specified in the first follow call, is not added into the request. Should I specify it every time?

**Comment by petejohanson** [comment]
Until I have a chance to add the automatic Accept header generation based on registered extensions, you can either:

1. Specify it in each call to `followOne`/`followAll`.
1. Add it to the default headers in the AngularJS $http service itself.

**Comment by XVincentX** [comment]
Adding it to http service will fit my current use case, but woud be "dangerous" for larger applications.

Thank you again for your help. Looking forward to see your update :+1: 
Keep up the great work!

**Comment by petejohanson** [comment]
@XVincentX Yes, that certainly is dangerous, polluting the global scope like that.

Please give angular-hy-res v0.0.15 a try, I've added the automatic Accept header generation based on registered extensions.

**Comment by XVincentX** [comment]
Working as expected! Great!

**Comment by petejohanson** [comment]
Ok, great. I'm going to close this, feel free to re-open if needed.

Thanks.
