### ISSUE TITLE
Nip: module name in lowerCamelCase

### ISSUE THREAD

**Issue by XVincentX** [petejohanson/angular-hy-res#7]
Directly from batarang:

![image](https://cloud.githubusercontent.com/assets/1416224/7464152/a2a224ac-f2c0-11e4-8ece-6a03941e6949.png)

**Comment by petejohanson** [comment]
Hmmm... since the convention is to use the first lowercase as an acronym/shorthand for the project itself, e.g. `ng` for Angular, I wonder if perhaps we should use:

* `hrCore`
* `hrHal`
* `hrSiren`
* etc

Thoughts?

**Comment by XVincentX** [comment]
Looks like it is the way you should go with thatl
