### ISSUE TITLE
Unwrap object from hy-res metadata.

### ISSUE THREAD

**Issue by XVincentX** [petejohanson/angular-hy-res#8]
Returned responses have got a lot of metadata due to hy-res intervention.
Would be nice to have got an _unwrap_ method that could return the raw object without `$follow` functions and all that stuff.

**Comment by petejohanson** [comment]
@XVincentX The hy-res README has the following entry:

* Store raw http response data in resource property, e.g. `res.$raw`

Would that satisfy your needs?

**Comment by XVincentX** [comment]
It should; however it is not documented into _angular_hy_res_.
I'll have a try.

**Comment by petejohanson** [comment]
No, this isn't implemented yet, I just wanted to check if I implemented that functionality, if it would satisfy your request.

**Comment by XVincentX** [comment]
I am just thinking about...I am not really sure if it will make sense.
I think it would be useful (especially for debugging purposes). However, usually the raw data will never be enough. For example, in Siren, I definitely need the actions to create the forms accordingly...

**Comment by petejohanson** [comment]
I've been looking at the Collection+Json spec recently thinking about how I would create an extension to support that format, and I think the hy-res API will need to evolve a bit to support it.

In particular, all the *data* in C+J is encapsulated in JSON l per field, like:

    { "name": "title", "value": "My Blog Post", "prompt": "Title" }

AFAICT, this is to support the PUT to replace item state operations, and allow UIs to display labels/prompts with each field that might be updated before a PUT.

As such... the simplistic " resource data will be a simple JSON object" assumption in hy-res doesn't quite cut it.

As such, we might need something like `Resource#field(name) => Object` and `Resource#val(name) => Field value`. Then it would also make sense to have `Resource#fields() => Array`.

More to ponder.

**Comment by petejohanson** [comment]
@XVincentX My understanding of the AngularJS conventions is that double `$$` prefixed properties/method are implicitly 'private' and only for internal use. It allows using prototype functions that access "private state", instead of having to add instance functions with access to true "private" scoped variables. Thus `$$forms` is used internally by the public `$form(rel)`.

**Comment by XVincentX** [comment]
That's cool! Could you expand how did you made it?

**Comment by petejohanson** [comment]
There is a new property on `Resource` called `$response` that is populated async once the resource resolves.

**Comment by petejohanson** [comment]
The API docs will be updated once I publish a new release with the changes.
